/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author Marco
 */
public class menuJFrame extends javax.swing.JFrame
{

    Image imagen = new ImageIcon(getClass().getResource("/imagenes/menuicon.png")).getImage();
    ButtonGroup grupo1;
    public OptionPanel1 op1;
    public OptionPanel2 op2;
    public OptionPanel3 op3;

    /**
     * Creates new form menuJFrame
     */
    public menuJFrame()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(imagen);
        grupo1 = new ButtonGroup();
        grupo1.add(horasTreintaYDos);
        grupo1.add(horasSesentaYCuatro);
        grupo1.add(horasNoventaYSeis);
        grupo1.add(horasCientoVeinteYOcho);

        op1 = new OptionPanel1();
        op2 = new OptionPanel2();
        op3 = new OptionPanel3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        horasTreintaYDos = new javax.swing.JRadioButton();
        horasSesentaYCuatro = new javax.swing.JRadioButton();
        horasNoventaYSeis = new javax.swing.JRadioButton();
        horasCientoVeinteYOcho = new javax.swing.JRadioButton();
        botonPonderar = new javax.swing.JButton();
        botonAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horasTreintaYDos.setForeground(new java.awt.Color(255, 255, 255));
        horasTreintaYDos.setText("32 Horas");
        horasTreintaYDos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                horasTreintaYDosActionPerformed(evt);
            }
        });
        jPanel1.add(horasTreintaYDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        horasSesentaYCuatro.setForeground(new java.awt.Color(255, 255, 255));
        horasSesentaYCuatro.setText("64 Horas");
        jPanel1.add(horasSesentaYCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        horasNoventaYSeis.setForeground(new java.awt.Color(255, 255, 255));
        horasNoventaYSeis.setText("96 Horas");
        jPanel1.add(horasNoventaYSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        horasCientoVeinteYOcho.setForeground(new java.awt.Color(255, 255, 255));
        horasCientoVeinteYOcho.setText("128 Horas");
        jPanel1.add(horasCientoVeinteYOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        botonPonderar.setText("Ponderar calificaciones");
        botonPonderar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonPonderarActionPerformed(evt);
            }
        });
        jPanel1.add(botonPonderar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        botonAbout.setText("Acerca de...");
        botonAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonAboutActionPerformed(evt);
            }
        });
        jPanel1.add(botonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELIGE UNA ESTRUCTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menubg.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 310, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horasTreintaYDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasTreintaYDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasTreintaYDosActionPerformed

    private void botonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAboutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new aboutJFrame().setVisible(true);
    }//GEN-LAST:event_botonAboutActionPerformed

    private void botonPonderarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonPonderarActionPerformed
    {//GEN-HEADEREND:event_botonPonderarActionPerformed
        if (horasTreintaYDos.isSelected())
        {
            this.setVisible(false);
            op1.setVisible(true);
        }
        else if (horasSesentaYCuatro.isSelected() || horasNoventaYSeis.isSelected())
        {
            this.setVisible(false);
            op2.setVisible(true);
        }
        else if (horasCientoVeinteYOcho.isSelected())
        {
            this.setVisible(false);
            op3.setVisible(true);
        }
    }//GEN-LAST:event_botonPonderarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new menuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton botonAbout;
    private javax.swing.JButton botonPonderar;
    private javax.swing.JRadioButton horasCientoVeinteYOcho;
    private javax.swing.JRadioButton horasNoventaYSeis;
    private javax.swing.JRadioButton horasSesentaYCuatro;
    private javax.swing.JRadioButton horasTreintaYDos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
