/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Mati
 */
public class OptionPanel1 extends javax.swing.JFrame implements FocusListener
{

    Image imagen = new ImageIcon(
            getClass().getResource("/imagenes/menuicon.png")).getImage();

    Ponderaciones calculo;

    double[] epeNotas = new double[5];
    double[] evaNotas = new double[4];

    JTextField[] epesField;
    JTextField[] evasField;

    public OptionPanel1()
    {
        epesField = new JTextField[4];
        evasField = new JTextField[4];
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(imagen);
        focusListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        epe1Field = new javax.swing.JTextField();
        epe2Field = new javax.swing.JTextField();
        epe3Field = new javax.swing.JTextField();
        epe4Field = new javax.swing.JTextField();
        eva1Field = new javax.swing.JTextField();
        eva2Field = new javax.swing.JTextField();
        eva3Field = new javax.swing.JTextField();
        eva4Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        examenField = new javax.swing.JTextField();
        botonCalcularNota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        notaPresLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        notaFinalLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        derechoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTRUCTURA 32 HORAS");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        epe1Field.setText("0.0");
        jPanel1.add(epe1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, -1));

        epe2Field.setText("0.0");
        jPanel1.add(epe2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 40, -1));

        epe3Field.setText("0.0");
        jPanel1.add(epe3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 40, -1));

        epe4Field.setText("0.0");
        epe4Field.setEnabled(false);
        jPanel1.add(epe4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 40, -1));

        eva1Field.setText("0.0");
        jPanel1.add(eva1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 40, -1));

        eva2Field.setText("0.0");
        jPanel1.add(eva2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 40, -1));

        eva3Field.setText("0.0");
        eva3Field.setEnabled(false);
        jPanel1.add(eva3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 40, -1));

        eva4Field.setText("0.0");
        eva4Field.setEnabled(false);
        jPanel1.add(eva4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EPE 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EPE 2");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EPE 3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EPE 4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EVA 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EVA 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EVA 3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EXAMEN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 50, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EVA 4");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        examenField.setText("0.0");
        examenField.setEnabled(false);
        jPanel1.add(examenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 40, -1));

        botonCalcularNota.setText("Calcular nota");
        botonCalcularNota.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonCalcularNotaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcularNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("NOTA PRESENTACION:");

        notaPresLabel.setText("NO CALCULADA");

        jLabel12.setText("NOTA FINAL                :");

        notaFinalLabel.setText("NO CALCULADA");

        jLabel11.setText("ESTADO ALUMNLO      :");

        estadoLabel.setText("NO CALCULADO");

        jLabel13.setText("DERECHO A EXAMEN  :");

        derechoLabel.setText("NO CALCULADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notaPresLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoLabel)
                            .addComponent(notaFinalLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(derechoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(notaPresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(notaFinalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(estadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(derechoLabel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 100));

        jButton1.setText("Vovler");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menubg.jpg"))); // NOI18N
        background.setToolTipText("");
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 541, 278));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularNotaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCalcularNotaActionPerformed
    {//GEN-HEADEREND:event_botonCalcularNotaActionPerformed
        double[] notas = new double[9];
        double[] resultados = new double[2];

        try
        {

            notas[0] = Double.parseDouble(epe1Field.getText());
            notas[1] = Double.parseDouble(epe2Field.getText());
            notas[2] = Double.parseDouble(epe3Field.getText());
            notas[3] = Double.parseDouble(epe4Field.getText());
            notas[4] = Double.parseDouble(eva1Field.getText());
            notas[5] = Double.parseDouble(eva2Field.getText());
            notas[6] = Double.parseDouble(eva3Field.getText());
            notas[7] = Double.parseDouble(eva4Field.getText());
            notas[8] = Double.parseDouble(examenField.getText());

        }
        catch (Exception Ex)
        {

            JOptionPane.showMessageDialog(null, "¡Error! \n\n"
                    + Ex.getMessage(), "Advertencia",
                    JOptionPane.WARNING_MESSAGE);

        }

        if (examenField.isEnabled())
        {
            calculo = new Ponderaciones(notas, true);
            resultados = calculo.Ponderar32();
            notaPresLabel.setText(Double.toString(resultados[0]));
            notaFinalLabel.setText(Double.toString(resultados[1]));
            if (resultados[1] >= 4.0)
            {
                estadoLabel.setText("APROBADO");
            }
            else
            {
                estadoLabel.setText("REPROBADO");
            }
        }
        else if (!examenField.isEnabled())
        {
            calculo = new Ponderaciones(notas, false);
            resultados = calculo.Ponderar32();
            notaPresLabel.setText(Double.toString(resultados[0]));
            notaFinalLabel.setText(Double.toString(resultados[1]));
            if (resultados[1] >= 4.0)
            {
                estadoLabel.setText("APROBADO");
            }
            else
            {
                estadoLabel.setText("REPROBADO");
            }
        }
    }//GEN-LAST:event_botonCalcularNotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        this.setVisible(false);
        formularios.loginJFrame.menuInterface.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Esta funcion sirve para escuchar los eventos de cada text field donde van
     * las notas, se inicializa y se guardan en un array
     */
    public void focusListener()
    {

        epe1Field.addFocusListener(this);
        epe2Field.addFocusListener(this);
        epe3Field.addFocusListener(this);
        epe4Field.addFocusListener(this);
        eva1Field.addFocusListener(this);
        eva2Field.addFocusListener(this);
        eva3Field.addFocusListener(this);
        eva4Field.addFocusListener(this);
        epesField[0] = epe1Field;
        epesField[1] = epe2Field;
        epesField[2] = epe3Field;
        epesField[3] = epe4Field;
        evasField[0] = eva1Field;
        evasField[1] = eva2Field;
        evasField[2] = eva3Field;
        evasField[3] = eva4Field;

    }

    public void ExamenChecker()
    {

        try
        {
            /**
             * Almacenar todas las notas de las epes de los text fields
             * correspondientes
             */
            int count = 0;
            for (JTextField i : epesField)
            {

                if (Double.parseDouble(i.getText()) != 0)
                {
                    epeNotas[count] = Double.parseDouble(i.getText());
                    count++;
                }
                if (i.getText().equals(""))
                {
                    i.setText(Double.toString(0));
                }

            }

            /**
             * Almacenar todas las notas de las evas de los text fields
             * correspondientes
             */
            count = 0;
            for (JTextField i : evasField)
            {

                if (Double.parseDouble(i.getText()) != 0)
                {
                    evaNotas[count] = Double.parseDouble(i.getText());
                    count++;
                }
                if (i.getText().equals(""))
                {
                    i.setText(Double.toString(0));
                }

            }

            /**
             * Calcular todas las evas y ver si da rojo para almacenar su
             * resultado como una nota epe en epeNotas[4]
             */
            double sumador = 0;
            for (int i = 0; i < evaNotas.length; i++)
            {

                sumador += evaNotas[i];

            }
            epeNotas[4] = sumador / 2;

            /**
             * Revisar si todas las notas son mayores a 4.0 para poder
             * interactuar con la interfaz y informar al usuario de su situacion
             * en tiempo real
             */
            count = 0;
            for (int i = 0; i < 5; i++)
            {
                if (epeNotas[i] < 4.0 && epeNotas[i] != 0)
                {
                    examenField.setEnabled(true);
                    derechoLabel.setText("SI");
                    break;
                }
                else
                {
                    count++;
                }
            }

            if (count == 5)
            {
                examenField.setEnabled(false);
                examenField.setText("0");
                derechoLabel.setText("NO");
            }

        }
        catch (Exception ex)
        {
            for (JTextField i : epesField)
            {
                    i.setText(Double.toString(0));
            }
            
            for (JTextField i : evasField)
            {
                i.setText(Double.toString(0));
            }
                       
            JOptionPane.showMessageDialog(null, "No puedes colocar caracteres "
                    + "incorrectos ni ocupar \"comas\" en los campos para "
                    + "ingresar las notas ni dejarlos vacios \n\nError: "
                    + ex.getMessage(),
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            
            
        }

    }

    @Override
    public void focusGained(FocusEvent e)
    {
        ExamenChecker();
    }

    @Override
    public void focusLost(FocusEvent e)
    {
        ExamenChecker();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OptionPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OptionPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OptionPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OptionPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OptionPanel1().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton botonCalcularNota;
    private javax.swing.JLabel derechoLabel;
    private javax.swing.JTextField epe1Field;
    private javax.swing.JTextField epe2Field;
    private javax.swing.JTextField epe3Field;
    private javax.swing.JTextField epe4Field;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField eva1Field;
    private javax.swing.JTextField eva2Field;
    private javax.swing.JTextField eva3Field;
    private javax.swing.JTextField eva4Field;
    private javax.swing.JTextField examenField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel notaFinalLabel;
    private javax.swing.JLabel notaPresLabel;
    // End of variables declaration//GEN-END:variables

}
